[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "libreoffice-still"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3.11 -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
